version: '3.4'

services:
  suitecloud-cli:
    image: skumail/suitecloud-cli:latest
    volumes:
      - suitecloud-cli-config:/home/node/.suitecloud-sdk
      - .:/usr/src/app
volumes:
  suitecloud-cli-config:
    name: suitecloud-cli-config
